<?php
/**
 * ACF Field Group Registration
 *
 * Registers all Advanced Custom Fields field groups programmatically using
 * acf_add_local_field_group(). This includes field groups for:
 * - Customer data (reference_customer post type)
 * - Location data (reference_location post type)
 * - Reference metadata (reference post type)
 *
 * Programmatic registration provides better performance and version control
 * compared to JSON-based field imports.
 *
 * @package JPKCom_ACF_References
 * @since   1.0.0
 */

declare(strict_types=1);

if ( ! defined( constant_name: 'WPINC' ) ) {
    die;
}

/**
 * Register ACF field groups for references, customers, and locations.
 *
 * Hooks into ACF's 'acf/include_fields' action to programmatically register
 * all field groups. Includes fields for:
 * - Customer website URL and logo
 * - Location address components (place, zip, street, region, country)
 * - Reference metadata (URL, description, customer, location, year, gallery, taxonomies, featured status, expiry date)
 *
 * @since 1.0.0
 * @return void
 */
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dcf8044f518',
	'title' => 'Kundendaten',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dcf805e6798',
			'label' => 'Kundenwebseite',
			'name' => 'reference_customer_url',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'Geben Sie hier eine Verlinkung/URL zur Kundenwebseite an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'return_format' => 'array',
			'allow_in_bindings' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dcf8c63df61',
			'label' => 'Kundenlogo',
			'name' => 'reference_customer_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Wählen Sie hier das Kundenlogo aus.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 1,
			'preview_size' => 'thumbnail',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de31fde1264',
			'label' => 'Referenzen',
			'name' => 'reference_customer_references',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Verknüpfte Referenzen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'post_type' => array(
				0 => 'reference',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_6926c1e3ff554',
			),
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'reference_customer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'acfml_field_group_mode' => 'translation',
) );

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_6925b07d23505',
	'title' => 'Referenz Details',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6926c996758cf',
			'label' => 'eigene URL die Referenz (intern oder extern)',
			'name' => 'reference_url',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'Wenn die Referenz keine eigene Detailseite besitzen soll, geben Sie bitte hier eine interne oder externe URL ein, zu der die URL der Detailseite weiterleiten soll.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'return_format' => 'array',
			'allow_in_bindings' => 1,
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6925b07e1022d',
			'label' => 'Kurzbeschreibung',
			'name' => 'reference_short_description',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Hier bitte ein kurze Beschreibung eingeben.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 0,
			'key' => 'field_6926c1e3ff554',
			'label' => 'Referenzkunde',
			'name' => 'reference_customer',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Wählen Sie hier einen Kunden aus.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'post_type' => array(
				0 => 'reference_customer',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_68de31fde1264',
			),
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 0,
			'key' => 'field_6926c2ae274c6',
			'label' => 'Referenz Ort',
			'name' => 'reference_location',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Wählen Sie hier einen Ort aus.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'post_type' => array(
				0 => 'reference_location',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_68de308b46c75',
			),
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_6926c3e18a816',
			'label' => 'Jahr',
			'name' => 'reference_year',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Geben Sie die Jahreszahl ein.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'default_value' => '',
			'min' => 1,
			'max' => 9999,
			'allow_in_bindings' => 1,
			'placeholder' => 'z. B. 2025',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6926c6c44be82',
			'label' => 'Bildergalerie',
			'name' => 'reference_image_gallery',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'Fügen Sie hier Bilder zur Galerie hinzu.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6926daaa48bf8',
			'label' => 'Referenz Typ',
			'name' => 'reference_type',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Wählen Sie den Referenz Typ.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'taxonomy' => 'reference-type',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6926db6aa3358',
			'label' => 'Referenz Filter 1',
			'name' => 'reference_filter_1',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Wählen Sie den Referenz Filter Nr. 1.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'taxonomy' => 'reference-filter-1',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6926dbb57e9d7',
			'label' => 'Referenz Filter 2',
			'name' => 'reference_filter_2',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Wählen Sie den Referenz Filter Nr. 2.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'taxonomy' => 'reference-filter-2',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_6926ca65c4cb2',
			'label' => 'Hervorgehobenes Referenz?',
			'name' => 'reference_featured',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'message' => 'Hervorgehobene Referenzen erscheinen bei Suchanfragen oben und können optisch anders dargestellt werden.',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nein',
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_6926cb20cf668',
			'label' => 'Referenz Ablaufdatum',
			'name' => 'reference_expiry_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Geben Sie bei Bedarf ein Ablaufdatum an, an dem diese Referenz ausgeblendet werden sollen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd.m.Y',
			'return_format' => 'Y-m-d',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'reference',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'acfml_field_group_mode' => 'translation',
) );

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dcf113ad7e1',
	'title' => 'Referenzort',
	'fields' => array(
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf11403af0',
			'label' => 'Ort',
			'name' => 'reference_location_place',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier den Ort als Adresse an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Ort',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf1ad9046c',
			'label' => 'PLZ',
			'name' => 'reference_location_zip',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Geben Sie hier die Postleitzahl an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'default_value' => '',
			'min' => 0,
			'max' => 99999,
			'allow_in_bindings' => 1,
			'placeholder' => 'PLZ',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf1d89046d',
			'label' => 'Straße und Hausnummer',
			'name' => 'reference_location_street',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier die Straße und Hausnummer an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Straße und Hausnummer',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de70b4be3b7',
			'label' => 'Region/Bundesland',
			'name' => 'reference_location_region',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier eine Region oder Bundesland an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Region oder Bundesland',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf1ef9046e',
			'label' => 'Land',
			'name' => 'reference_location_country',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier das Land an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Land',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de308b46c75',
			'label' => 'Referenzen',
			'name' => 'reference_location_references',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Verknüpfte Referenzen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'post_type' => array(
				0 => 'reference',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_6926c2ae274c6',
			),
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'reference_location',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'acfml_field_group_mode' => 'translation',
) );
} );
